### ISSUE TITLE
is it only for me or does all of the aa not work?

### ISSUE THREAD

**Issue by mineo210** [raspbianlike/Hitlerhook#6]
legit trolling doesnt seem to be working. (jumped into a bot game with "bot_mimic" and "sv_showlagcompensation"

and smooth aim doesnt seem to be working as well for me :/

is it that csgo has fixed all the aa? or its just something that is wrong with the code or aa?

**Comment by raspbianlike** [comment]
Thats why it is called *legit trolling* its a fakehead and not visible
/closed
